name: fitness
description: A new Flutter project. 
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  flutter_riverpod: ^2.3.6
  go_router: 7.1.1
  build_runner: ^2.4.5
  riverpod_generator: ^2.2.3
  riverpod_annotation: 2.1.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  url_launcher: ^6.1.14
  firebase_ui_firestore: ^1.5.8
  shimmer: ^3.0.0
  firebase_crashlytics: ^3.3.5
  firebase_analytics: ^10.4.5
  sticky_headers: "^0.3.0"
  dio: ^5.3.3
  cached_network_image: ^3.3.0
  font_awesome_flutter: ^10.6.0
  sliver_tools: ^0.2.12
  google_fonts: ^6.1.0
  flutter_ruler_picker: ^1.0.6
  horizontal_blocked_scroll_physics: ^4.0.1
  dio_cache_interceptor_hive_store: ^3.2.1
  path_provider: ^2.1.1
  async: ^2.11.0
  collection: ^1.17.2
  dio_cache_interceptor: ^3.4.4

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
 
flutter:
 
  uses-material-design: true
  assets:
    - assets/images/