// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQW-jfPPDi6qoP5Xb6WBIEVjZEA1dXKNQ',
    appId: '1:576897811959:web:3c2651a17c1c04801a1af2',
    messagingSenderId: '576897811959',
    projectId: 'fitness-app-e10cd',
    authDomain: 'fitness-app-e10cd.firebaseapp.com',
    storageBucket: 'fitness-app-e10cd.appspot.com',
    measurementId: 'G-EG65PH8X30',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMyFzi3C-_ZOQ0QLk4X6gDm74EEfYHDm4',
    appId: '1:576897811959:android:af556a74a0f62ffe1a1af2',
    messagingSenderId: '576897811959',
    projectId: 'fitness-app-e10cd',
    storageBucket: 'fitness-app-e10cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlgHmT63GXMFuLNxUQ1d_hxl8fRyZQ8hg',
    appId: '1:576897811959:ios:191ca68440cbdf801a1af2',
    messagingSenderId: '576897811959',
    projectId: 'fitness-app-e10cd',
    storageBucket: 'fitness-app-e10cd.appspot.com',
    iosBundleId: 'com.example.fitness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlgHmT63GXMFuLNxUQ1d_hxl8fRyZQ8hg',
    appId: '1:576897811959:ios:c6cce1a962a589e61a1af2',
    messagingSenderId: '576897811959',
    projectId: 'fitness-app-e10cd',
    storageBucket: 'fitness-app-e10cd.appspot.com',
    iosBundleId: 'com.example.fitness.RunnerTests',
  );
}
